apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jira-webhook-proxy
  name: jira-webhook-proxy
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: jira-webhook-proxy
  strategy: { }
  template:
    metadata:
      labels:
        app: jira-webhook-proxy
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: jira-webhook-proxy
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /app/config.yml
              subPath: config.yml
              name: config-map
      volumes:
        - name: config-map
          configMap:
            name: jira-webhook-proxy-config
