---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webhook-proxy
spec:
  host: webhook-proxy.apps.private.{{ .Values.region_hostname }}
  port:
    targetPort: http
  to:
    kind: Service
    name: webhook-proxy
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
