---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jira-webhook-proxy
spec:
  host: jira-webhook-proxy.apps.private.{{ .Values.region_hostname }}
  port:
    targetPort: 8080
  to:
    kind: Service
    name: jira-webhook-proxy
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
