apiVersion: v1
kind: Service
metadata:
  name: jira-webhook-proxy
spec:
  selector:
    app: jira-webhook-proxy
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
